import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Learning Three JS React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.grid}>
          <Link href="/basic" className={styles.card} rel="noopener noreferrer">
            <h2 className={inter.className}>
              Basics setup <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Original was done in webpack, but I want to do it in nextjs
            </p>
          </Link>
          <Link
            href="/position"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Position <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Exploring Postion Scale rotation and quaternion
            </p>
          </Link>
          <Link
            href="/groups"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Group <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instead of doing action on each and evey object we can group them,
              like brick and wall.
            </p>
          </Link>
          <Link
            href="/animation"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Animation <span>-&gt;</span>
            </h2>
            <p className={inter.className}>-</p>
          </Link>
          <Link
            href="/camera"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Camera <span>-&gt;</span>
            </h2>
            <p className={inter.className}>-</p>
          </Link>
        </div>
      </main>
    </>
  );
}
